### ISSUE TITLE
Org Detail screen

### ISSUE THREAD

**Issue by KitsuneNoctus** [MOB-2-9/Petulia-T1#1]
### User Story

**As a** user
**I can** visit the detail page of an organization
**so that** I can see the description and contact information

### Description

When choosing an item from the map, users can go to the details screen for that welfare organization. This screen will display:

- Name
- Address
- Location in a map
- Email
- Phone
- Url to website
- Links to social media if available
- Photo

### Resources:

[Petfinder API](https://www.petfinder.com/developers/v2/docs/#get-organization)

### Story Points

3 points - BE
6 points - FE

**Comment by amelinagzz** [comment]
Who is working on the Front End of this issue? Make sure to mock first how it's going to look and get feedback from the team or me. It can be digital or in paper. Try to use a simple interface that allows for SwiftUI elements to be used without much customization.

**Comment by amelinagzz** [comment]
The story points look a little low to me. I would say maybe 4 - 5 each. But ultimately it's up to you 👍🏼
