### ISSUE TITLE
Tabbar Navigation

### ISSUE THREAD

**Issue by anikamorris** [MOB-2-9/Petulia-T1#2]
### User Story

**As a** user
**I can** select different tabs
**so that** I can navigate between screens

### Description

Two main tabs:

Pets
Welfare Organization

### Resources:

https://www.hackingwithswift.com/quick-start/swiftui/adding-tabview-and-tabitem

**Additional context**

### Story Points

How many points is this story worth
3

**Comment by amelinagzz** [comment]
Who is doing the integration with the Welfare Organization page once it's done?
