### ISSUE TITLE
Sharing a result

### ISSUE THREAD

**Issue by caocmai** [MOB-2-9/Petulia-T1#8]
### User Story

**As a** user
**I can** share the information of a pet
**so that** more people can look at the results

### Description

In PetDetailView.swift, there will be a navigation item that when pressed, it will display a UIActivityController to share information about the Pet with a predefined template message.

Title: Help them find a home 💚
Message: 
"*name* is a *breed* 
Location: *location*
Phone:  *phone*"
and a url.

### Resources:

[UIActivityController](https://www.hackingwithswift.com/articles/118/uiactivityviewcontroller-by-example)

### Story Points

How many points is this story worth?
4 points

**Comment by amelinagzz** [comment]
This is done already, make sure it's attached to the PR.
